# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r:
  - 4.0

os:
  - linux
  - osx

cache:
  packages: true

notifications:
  email:
    recipients:
      - ben.goldstein@berkeley.edu
    on_success: change
    on_failure: change

install:
  - ./install_requirements.R
  - R CMD build packages/nimbleSMC
  - R CMD INSTALL *tar.gz --install-tests

script:
  - R CMD check *tar.gz --as-cran
  - Rscript ./run_tests.R

