# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r:
  - 4.0

dist: bionic
sudo: false

os:
  - linux
  - osx

cache:
  packages: true

notifications:
  email:
    recipients:
      - paciorek@berkeley.edu
    on_success: change
    on_failure: change

script:
  - R CMD build .
  - R CMD check *tar.gz --as-cran
  - R CMD INSTALL *tar.gz --install-tests
  - Rscript ./run_tests.R

branches:
  only:
    - master
    - devel
